### ISSUE TITLE
failed to create dataset while using --start option

### ISSUE THREAD

**Issue by interactyuvraj** [dnlbauer/WHAM#11]
Dear @dnlbauer

Thank you for implementing the WHAM code. It is beneficial for me and many more people who use umbrella sampling. 
I need some help with implementing it. When I use the --start option to skip some time series, it gives the following error.

Reason: Failed to create datasets.
Reason: No data points for interval 1000-100000000000000000000 in histogram boundaries: NCOL0.xvg. This is the final dataset. (NCOLO.xvg is my data set at a given window). 
However, without the --start option, the code works.  Could you please tell me where I am wrong? 
Your response is much needed. 

Thanks and Regards
Yuvraj Singh

**Comment by dnlbauer** [comment]
Hi,

For me it sounds like your `--start` parameter is set highter than the max. time value in one of your time series files. Therefore, after applying the filter, there are no data points left for this file.

Let me explain it by looking at a file together: `tests/data/COLVAR_0_2.xvg`. It has data for the time interval ranging from `t0=0.02` up to `tn=2.0`

```
0.020000  -0.377860
0.040000  0.010992
0.060000  0.123074
...
1.980000  0.280272
2.000000  0.127339
```

Therefore, when you use this file, you can set `--start` to anything between `0` and `2.0`. For example if you set it to `1.0`, the first half of the file will be discarded. But once you set `--start` to something higher than `2.0`, you get the exact same error you got for your data:

```bash
> wham -f metadata_convdt.dat --min 0 --max 0.1  --temperature 300 --bins 10 --start 2.1
...
Error: Failed to read data.
Reason: Failed to read time series from COLVAR_0-2.xvg
Reason: Time series is empty
```

This is because the check happens per file. **You cannot set the --start and --end parameters to values that would leave any of your time series files empty**. This is a precaution to make it obvious to you that you just excluded a whole time series file from your analysis (which is something you might not want to do). If you are sure that this is actually what you intended, you can supress this error with the `--ignore_empty` flag:

```bash
> wham -h
...
 --ignore_empty                 If this is set, do not fail if a histogram is empty.
```

**Comment by dnlbauer** [comment]
Hi,

For me it sounds like your --start parameter is set highter than the max. time value in one of your time series files. Therefore, after applying the filter, there are no data points left for this file.

Let me explain it by looking at a file together: tests/data/COLVAR_0_2.xvg. It has data for the time interval ranging from t0=0.02 up to tn=2.0

0.020000  -0.377860
0.040000  0.010992
0.060000  0.123074
...
1.980000  0.280272
2.000000  0.127339
Therefore, when you use this file, you can set --start to anything below 2.0. For example if you set it to 1.0, the first half of the file will be discarded. But once you set --start to 2.0, you get the exact same error you got for your data:

> wham -f metadata_convdt.dat --min 0 --max 0.1  --temperature 300 --bins 10 --start 2.0
...
Reading input files.
Error: Failed to read data.
Reason: Failed to create datasets.
Reason: No data points for interval 2-100000000000000000000 in histogram boundaries: COLVAR_0-2.xvg. This is the final dataset.
```

You cannot set the --start and --end parameters to values that would leave any of your time series files empty. This is a precaution to make it obvious to you that you just excluded a whole time series file from your analysis (which is something you might not want to do). If you are sure that this is actually what you intended, you can supress this error with the --ignore_empty flag. In this case, you are still warned but the calculation proceeds anyways:

> wham -h
...
 --ignore_empty                 If this is set, do not fail if a histogram is empty.

**Comment by interactyuvraj** [comment]
Hello. Thank you so much for your response. 
I initially misunderstood the purpose of the --start flag. Rather than discarding a specified number of rows, it designates the starting point for the time series data included in the calculation.

**Comment by interactyuvraj** [comment]
Thanks Again
