### ISSUE TITLE
The error about file format.

### ISSUE THREAD

**Issue by Rulong-Ma** [dnlbauer/WHAM#4]
Hi Daniel Bauer, There is an error about my data file when I used your AHAM to analysis my data. The error information is in the photo. Could you help to solve this problem? Thanks!
![wham_error](https://user-images.githubusercontent.com/48371827/236296051-f411f3cb-fe61-4288-bec4-4723cec176d0.png)

**Comment by dnlbauer** [comment]
@Rulong-Ma to me it looks like you are supplying an actual data file containing the histogram data to the metadata parameter (-f), and therefore the program does not find the columns it is looking for. The `-f` expects you to pass no actual data, but an overview of where this data is stored with bounndaries and force constants for the restraints. For example, for a 2d WHAM, you need to supply a metadata file with 5 columns in this column order: `data filename` `var1` `var2` `force constant acting on var 1` `force constant acting on var 2`. The first column should then points to files containing the histogram data for the respective parameter set with 3 columns (again, for 2d wham): `time or step` `var1` `var2`.

Make sure everything is of a correct format and matches this specification. For an example on how the metadata file and histogram files should be formatted for 2d wham, you can also have a look on the 2d wham example here: [metadata.dat](https://github.com/dnlbauer/WHAM/blob/master/example/2d_cyclic/metadata.dat)

Hope this helps!

**Comment by Rulong-Ma** [comment]
@dnlbauer Thank you for your reply. Now, I understand the error of the file. However, I do not know the force constant acting on var 1(or var2). The x_1 and x_2 in my file are the two angles of membrane protein in the classical molecular dynamics simulation.  I did not offer additional force on the protein. I do not know the force constant acting on x_1(or var1) in my simulation. Do you know how can I get force constant acting on x_1 ? Thanks.

**Comment by dnlbauer** [comment]
@Rulong-Ma if you didnt apply any additional forces, the force constants are likely to be 0.

However, in this case I do not see a reason to apply the WHAM method to your data. WHAM is generally used to "unbias" simulations with a biasing force acting on a reaction coordinate (the two angles in your case). If there are no such bias potentials applied, you do not need to do WHAM because there is nothing to unbias. In theory wham should still work though if there is no bias force, so you can try it (I am not entirely sure if there is a divide by 0 error hidden somewhere since I never though of applying a force of 0 😁 )

Nevertheless, if you do not have bias force, there is a more simple method to calculate free energy from your data. You can create a histogram from it, calculate the probability of your protein to be in a given bin from that histogramm data and directly obtain the free energy of the bins from their respective probabiltieis via $F(i)=-RTlog(P(i)/P(0))$ where i is the bin index and P(i) is the probability of obsesving the protein in state i calculated from the histogram counts.

**Comment by Rulong-Ma** [comment]
@dnlbauer Thank you for your reply. 
After I set force constants (0), WHAM does not work. It seems that WHAM does not work on my simulation data. 
However, I am interested in the simple method to calculate free energy ( F(i) =-RTlog( P(i) / P(0)) ).  (1) Could you tell me where this equation come from? any reference? (2) what P(0) mean? Thanks.

**Comment by dnlbauer** [comment]
P(0) would correspond to the ground state, or lowest energy state. If you think your sampling is sufficent you can assume that is is simply the sate with the highest probability. However, using this method is usually not feasable since you habe to sample quite a lot and protein systems tend to be to big to do that. That's why peaople do things like umbrella sampling in combination with WHAM and other enhanced sampling techniques.

For the equation, this is a direct application of the Boltzmann distribution. I dont have a good source for a derivation at hand.  However, the Boltzmann distribution is fundamental for statistical mechanics so you should be able to find a derivation in most books about stats. mech or thermodynamics. The wikipedia page is also a good start: https://en.wikipedia.org/wiki/Boltzmann_distribution
